version: '3'
 
services:
 
  bash:
    image: braintwister/ubuntu-18.04-cmake-3.15-clang-9-conan-1.19
    volumes:
      - home:/home/ubuntu
      - /home/ubuntu/projects:/opt/projects
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - USER_NAME=ubuntu
      - GROUP_NAME=ubuntu
    privileged: true
    stdin_open: true
    tty: true
 
volumes:
  home:
